### ISSUE TITLE
All-NaN slice encountered, stack blown

### ISSUE THREAD

**Issue by mfine** [swift-nav/piksi_tools#160]
Seeing stack traces in `master`:

```
ValueError: All-NaN slice encountered
ERROR:traits:Exception occurred in traits notification handler for object: <chaco.array_plot_data.ArrayPlotData object at 0x11c890410>, trait: data_changed, old value: <undefined>, new value: {'changed': ['ch3']}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/traits/trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/usr/local/lib/python2.7/site-packages/traits/trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "/usr/local/lib/python2.7/site-packages/chaco/plot.py", line 1061, in _data_update_handler
    source.set_data(self.data.get_data(name))
  File "/usr/local/lib/python2.7/site-packages/chaco/array_data_source.py", line 98, in set_data
    self._compute_bounds()
  File "/usr/local/lib/python2.7/site-packages/chaco/array_data_source.py", line 253, in _compute_bounds
    self._min_index = bounded_nanargmin(data.view(ndarray))
  File "/usr/local/lib/python2.7/site-packages/chaco/array_data_source.py", line 14, in bounded_nanargmin
    min = nanargmin(arr)
  File "/usr/local/lib/python2.7/site-packages/numpy/lib/nanfunctions.py", line 375, in nanargmin
    raise ValueError("All-NaN slice encountered”)
```

And the stack being popped:

![screen shot 2015-08-11 at 4 47 13 pm](https://cloud.githubusercontent.com/assets/60851/9214014/a681199a-404d-11e5-8e2d-49ec82bb6394.png)

**Comment by mfine** [comment]
This looked like a bad device sending in bad data. Closing.
