### ISSUE TITLE
Linux install error: Failed to execute script console

### ISSUE THREAD

**Issue by droter** [swift-nav/piksi_tools#709]
Traceback (most recent call last):
  File "piksi_tools/console/console.py", line 44, in <module>
  File "/tmp/pip-build-TuTcEi/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "piksi_tools/console/baseline_view.py", line 17, in <module>
  File "/tmp/pip-build-TuTcEi/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "site-packages/chaco/api.py", line 38, in <module>
  File "/tmp/pip-build-TuTcEi/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "site-packages/chaco/abstract_plot_renderer.py", line 7, in <module>
  File "/tmp/pip-build-TuTcEi/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "site-packages/chaco/plot_component.py", line 4, in <module>
  File "/tmp/pip-build-TuTcEi/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "site-packages/enable/api.py", line 21, in <module>
  File "/tmp/pip-build-TuTcEi/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "site-packages/enable/markers.py", line 18, in <module>
  File "/tmp/pip-build-TuTcEi/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "site-packages/enable/compiled_path.py", line 17, in <module>
  File "/tmp/pip-build-TuTcEi/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "site-packages/enable/toolkit.py", line 47, in <module>
  File "site-packages/enable/toolkit.py", line 40, in _init_toolkit
ImportError: Unable to import the image backend for the qt4 toolkit (reason: ['ImportError: /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1: undefined symbol: drmGetDevices2\n']).
Failed to execute script console

ubuntu 16.04 64

**Comment by droter** [comment]
Works in clean docker container.
