### ISSUE TITLE
Support SBP 2.3.13 and SBAS mode flag

### ISSUE THREAD

**Issue by nsirola** [swift-nav/piksi_tools#749]
The new SBAS_POSITION mode (https://github.com/swift-nav/piksi_firmware_private/pull/1759) causes console Solution tab to stop updating, with error:

```
Traceback (most recent call last):
KeyError: 6
  File "piksi_tools\console\solution_view.py", line 307, in pos_llh_callback
  File "site-packages\sbp\client\handler.py", line 172, in _call
```

Need to update libsbp pointer and add handling for SBAS mode (6).

**Comment by nsirola** [comment]
Fixed by https://github.com/swift-nav/piksi_tools/pull/750, closing.
