### ISSUE TITLE
ModuleNotFoundError: No module named 'handler'

### ISSUE THREAD

**Issue by adhityadwi** [swift-nav/piksi_tools#797]
Hello, I've got an error like this when running "

(Env_PIKSI) C:\Users\Adhitya\Documents\GNSS\GNSSPython\Env_PIKSI\piksi_tools>python -m piksi_tools.console.console
Traceback (most recent call last):
  File "c:\users\adhitya\anaconda3\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\adhitya\anaconda3\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Adhitya\Documents\GNSS\GNSSPython\Env_PIKSI\piksi_tools\piksi_tools\console\console.py", line 24, in <module>
    import sbp.client as sbpc
  File "C:\Users\Adhitya\Documents\GNSS\GNSSPython\Env_PIKSI\lib\site-packages\sbp\client\__init__.py", line 11, in <module>
    from handler import Handler
ModuleNotFoundError: No module named 'handler'

How to resolve this problem?

Thanks

**Comment by adhityadwi** [comment]
Ok, I resolved the issue by using python 2.7 version in virtualenv.
